### ISSUE TITLE
Explanation Required

### ISSUE THREAD

**Issue by gjkaur** [ritulahoti/BraTS#1]
Hi Ritulahoti

Can you please elaborate your code with other files used in this complete process, folder structure and model explanation.

**Comment by ritulahoti** [comment]
> model

Hi Gurinderjeet

This is not my original work. I have to make this upload public due to access issue on other platform. However, you can find the entire code in the link; https://github.com/IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization
I hope this helps.
